[package]
name = "aoc_2023"
version = "0.1.0"
description = "Advent of Code 2023 solutions"
edition = "2021"

[dependencies]
regex = "1"

[[bin]]
name = "01"
path = "./src/01/main.rs"

[[bin]]
name = "02"
path = "./src/02/main.rs"

[[bin]]
name = "03"
path = "./src/03/main.rs"
